project:
  type: book
  resources:
  - webr-serviceworker.js
  - webr-worker.js
  - coi-serviceworker.js
book:
  title: HuGen2080 book
  author: Daniel E. Weeks
  date: today
  chapters:
  - index.qmd
  - intro.qmd
  - logistics.qmd
  - Readings.qmd
  - statsBasics.qmd
  - gitIntro.qmd
  - Git_commands.Qmd
  - Basic_Unix_commands.Qmd
  - Ascertainment.qmd
  - LODscores.qmd
  - summary.qmd
  - references.qmd
  appendices:
  - TechnicalDetails.qmd
  - webR_test.qmd
bibliography: references.bib
format:
  html:
    theme: cosmo
    link-external-icon: true
    link-external-newwindow: true
    link-external-filter: ^(?:http:|https:)\/\/danieleweeks\.github\.io\/HuGen2080
    css: include/webex.css
    include-after-body: include/webex.js
filters: 
   - webr
